# Copy this file to ~/.config/print-markdown/options and edit it.
# print-markdown-finder.sh reads these options and passes them to print-markdown.

--theme clean
--paper A4
--orientation portrait
--font-size 13
--margin 46
--print
--print-option ARCMode=CMBW
--sides one-sided
